name: Publicar

on:
  push:
    branches:
      - principal
jobs:
  release:
    name: Publicar
    runs-on: ubuntu-latest
    steps:
      - name: Obtener actualización del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Instalar dependencias
        run: yarn install --frozen-lockfile
      - name: Exportar librería
        run: yarn build
      - name: 🐘 Publicar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
